
package org.itson.bda.BancoMB.bancoMB.dlg;


public class InicioSesion extends javax.swing.JDialog {

    /**
     * Creates new form InicioSesion
     * @param parent
     * @param modal
     */
    public InicioSesion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlFondoAzul = new javax.swing.JPanel();
        TxtFldCorreoElectronico = new javax.swing.JTextField();
        TxtFldClave = new javax.swing.JTextField();
        LblBienvenido = new javax.swing.JLabel();
        LblCorreoElectronico = new javax.swing.JLabel();
        LblClave = new javax.swing.JLabel();
        BtnRegresar = new javax.swing.JButton();
        BtnIniciarSesion = new javax.swing.JButton();
        LblBancoMB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PnlFondoAzul.setBackground(new java.awt.Color(0, 102, 153));

        LblBienvenido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        LblBienvenido.setText("Bienvenido");

        LblCorreoElectronico.setForeground(new java.awt.Color(204, 204, 255));
        LblCorreoElectronico.setText("Correo eléctronico");

        LblClave.setForeground(new java.awt.Color(204, 204, 255));
        LblClave.setText("Clave");

        BtnRegresar.setText("Regresar");

        BtnIniciarSesion.setText("Iniciar sesión");

        javax.swing.GroupLayout PnlFondoAzulLayout = new javax.swing.GroupLayout(PnlFondoAzul);
        PnlFondoAzul.setLayout(PnlFondoAzulLayout);
        PnlFondoAzulLayout.setHorizontalGroup(
            PnlFondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnRegresar)
                .addGap(47, 47, 47)
                .addGroup(PnlFondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlFondoAzulLayout.createSequentialGroup()
                        .addGap(0, 24, Short.MAX_VALUE)
                        .addComponent(LblBienvenido)
                        .addGap(166, 166, 166))
                    .addGroup(PnlFondoAzulLayout.createSequentialGroup()
                        .addGroup(PnlFondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblClave)
                            .addComponent(LblCorreoElectronico)
                            .addComponent(TxtFldCorreoElectronico)
                            .addComponent(TxtFldClave, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(PnlFondoAzulLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(BtnIniciarSesion)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PnlFondoAzulLayout.setVerticalGroup(
            PnlFondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoAzulLayout.createSequentialGroup()
                .addComponent(LblBienvenido)
                .addGap(26, 26, 26)
                .addComponent(LblCorreoElectronico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtFldCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(LblClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtFldClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(BtnIniciarSesion)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlFondoAzulLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnRegresar)
                .addContainerGap())
        );

        LblBancoMB.setFont(new java.awt.Font("Yu Gothic Medium", 3, 14)); // NOI18N
        LblBancoMB.setForeground(new java.awt.Color(0, 0, 102));
        LblBancoMB.setText("Banco MB");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondoAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(LblBancoMB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblBancoMB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PnlFondoAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIniciarSesion;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JLabel LblBancoMB;
    private javax.swing.JLabel LblBienvenido;
    private javax.swing.JLabel LblClave;
    private javax.swing.JLabel LblCorreoElectronico;
    private javax.swing.JPanel PnlFondoAzul;
    private javax.swing.JTextField TxtFldClave;
    private javax.swing.JTextField TxtFldCorreoElectronico;
    // End of variables declaration//GEN-END:variables
}
